name = "irm-extra"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "irm-extra-db"
database_id = "ddc91a90-fbf7-4054-b720-67e004bc57bc"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "irm-extra-uploads"

[vars]
APP_ENV = "production"
APP_URL = "https://irmextra.com"
SESSION_SECRET = "8f3a92e7c15b4d6a9f0e2c7b8a1d4f6e3c9b2a5d8e1f4c7b0a3d6e9f2c5b8a1d"
RESEND_API_KEY = "re_xxxxxxxxxxxxxxxxxx"
MAIL_FROM_ADDRESS = "noreply@irmextra.com"
MAIL_FROM_NAME = "IRM Extra"
