name = "irm-extra"
main = ".open-next/worker.js"

compatibility_date = "2026-08-21"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "irm-extra-db"
database_id = "ddc91a90-fbf7-4054-b720-67e004bc57bc"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "irm-extra-uploads"

[vars]
APP_ENV = "production"
APP_URL = "https://irmextra.com"
MAIL_FROM_ADDRESS = "noreply@irmextra.com"
MAIL_FROM_NAME = "IRM Extra"
